# Generated by Django 4.2.1 on 2023-05-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEGAJO', models.BigIntegerField()),
                ('NOMBRE', models.CharField(max_length=255)),
                ('APELLIDO', models.CharField(max_length=255)),
                ('GERENCIA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licencias.gerencia')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRUPO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.grupo')),
                ('USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.usuarios')),
            ],
            options={
                'verbose_name': 'Usuarios',
                'verbose_name_plural': 'Usuarios Asignados',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='ADMINISTRADOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_administrador', to='licencias.usuarios'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='USUARIOS',
            field=models.ManyToManyField(to='licencias.usuarios'),
        ),
    ]
