# Generated by Django 4.2.1 on 2023-05-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0002_grupo_licencias_asignadas_grupo_licencias_libres'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupousuarios',
            name='FECHA_FINAL',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupousuarios',
            name='FECHA_INICIO',
            field=models.DateField(blank=True, null=True),
        ),
    ]
