# Generated by Django 4.2.1 on 2023-05-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0003_grupousuarios_fecha_final_grupousuarios_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='NOMBRE',
        ),
        migrations.AlterUniqueTogether(
            name='grupousuarios',
            unique_together={('GRUPO', 'USUARIO')},
        ),
    ]
