# Generated by Django 4.2.1 on 2023-05-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0005_licencias_grupousuarios_licencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupousuarios',
            name='LICENCIA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licencias.licencias'),
        ),
    ]
