# Generated by Django 2.2.28 on 2023-05-22 19:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=255, unique=True)),
                ('VERSION', models.CharField(max_length=150)),
                ('APLICACION_INTERNA', models.BooleanField(default=False)),
                ('ULTIMA_MODIFICACION', models.DateField(auto_now_add=True)),
                ('APLICA_VENCIMIENTO', models.BooleanField(default=False)),
                ('FECHA_VENCIMIENTO', models.DateField(blank=True, null=True)),
                ('INFO', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aplicacion',
                'verbose_name_plural': 'ABM Aplicaciones',
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GERENCIA', models.CharField(max_length=50)),
                ('PROCESOS_ACTIVOS', models.IntegerField(blank=True, null=True)),
                ('HORAS_BENEFICIO', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Gerencia',
                'verbose_name_plural': 'ABM Gerencias',
            },
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.TextField(blank=True, null=True)),
                ('Fecha', models.DateField(blank=True, null=True)),
                ('HoraEjecucion', models.TextField(blank=True, null=True)),
                ('Proceso', models.TextField(blank=True, null=True)),
                ('Gerencia', models.TextField(blank=True, null=True)),
                ('Mensaje', models.TextField(blank=True, null=True)),
                ('Duracion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Duracion Minutos')),
                ('Server', models.TextField(blank=True, null=True)),
                ('Paquete', models.TextField(blank=True, null=True)),
                ('Comentarios', models.CharField(blank=True, max_length=120, null=True)),
                ('clave', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Monitoreo',
                'verbose_name_plural': 'Monitoreos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_APELLIDO', models.CharField(max_length=120)),
                ('EMPRESA', models.CharField(blank=True, max_length=60, null=True)),
                ('CARGO', models.CharField(blank=True, max_length=50, null=True)),
                ('MAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('TELEFONO', models.CharField(blank=True, max_length=20, null=True)),
                ('COMENTARIOS', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Desarrollador',
                'verbose_name_plural': 'ABM Desarrolladores',
            },
        ),
        migrations.CreateModel(
            name='robots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACTIVO', models.BooleanField(default=False)),
                ('NOMBRE', models.CharField(max_length=120, unique=True)),
                ('FECHA_PUESTA_PRD', models.DateField(blank=True, null=True)),
                ('ATENDIDO', models.CharField(choices=[('Atendido', 'Atendido'), ('Desatendido', 'Desatendido')], default='ATENDIDO', max_length=11)),
                ('ULTIMO_PAQUETE', models.CharField(blank=True, max_length=20, null=True)),
                ('ULTIMA_ACTUALIZACION', models.DateField(blank=True, null=True)),
                ('ARCHIVO_CONFIG', models.CharField(max_length=255)),
                ('RUTAS_INPUT', models.CharField(blank=True, max_length=255, null=True)),
                ('RUTAS_OUTPUT', models.CharField(blank=True, max_length=255, null=True)),
                ('DESCRIPCION_BREVE', models.TextField(blank=True, null=True)),
                ('COMENTARIOS', models.TextField(blank=True, null=True)),
                ('EJECUCIONES', models.IntegerField(blank=True, null=True)),
                ('ERRORES', models.IntegerField(blank=True, null=True)),
                ('FATAL', models.IntegerField(blank=True, null=True)),
                ('REPROCESAR', models.TextField(blank=True, null=True)),
                ('APLICACIONES_USADAS', models.ManyToManyField(to='administracion.Aplicacion')),
            ],
            options={
                'verbose_name': 'Robot',
                'verbose_name_plural': 'Robots',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_APELLIDO', models.CharField(max_length=120)),
                ('MAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('TELEFONO', models.CharField(blank=True, max_length=20, null=True)),
                ('COMENTARIOS', models.TextField(blank=True, null=True)),
                ('GERENCIA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.Gerencia')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'ABM Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.TextField()),
                ('FECHA_INICIO', models.DateField(blank=True, null=True)),
                ('FECHA_FIN', models.DateField(blank=True, null=True)),
                ('TIEMPO_INVERTIDO', models.TimeField(blank=True, default=datetime.timedelta(seconds=1800), null=True)),
                ('ESTADO', models.CharField(choices=[('No inciado', 'No inciado'), ('inciado', 'inciado'), ('Esperando Respuesta', 'Esperando Respuesta'), ('Finalizada', 'Finalizada')], default='No inciado', max_length=30)),
                ('GERENCIA_A_IMPUTAR', models.CharField(blank=True, max_length=255, null=True)),
                ('COMENTARIOS', models.TextField(blank=True, null=True)),
                ('ROBOT_ASOCIADO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.robots')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='servidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOSTNAME', models.CharField(max_length=20, unique=True)),
                ('IP', models.CharField(blank=True, max_length=20, null=True)),
                ('TIPO', models.CharField(choices=[('Desarrollo', 'Desarrollo'), ('Test', 'Test'), ('Produccion', 'Produccion')], default=1, max_length=20)),
                ('SISTEMA_OPERATIVO', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('Mac', 'Mac')], default=1, max_length=20)),
                ('PROCESADOR', models.CharField(blank=True, max_length=200, null=True)),
                ('MEMORIA_RAM', models.CharField(blank=True, max_length=20, null=True)),
                ('ARQUITECTURA', models.CharField(blank=True, max_length=20, null=True)),
                ('NOMBRE_COMPLETO', models.CharField(blank=True, max_length=50, null=True)),
                ('DOMINIO', models.CharField(blank=True, max_length=50, null=True)),
                ('COMENTARIOS', models.TextField(blank=True, null=True)),
                ('APLICACIONES_INSTALADAS', models.ManyToManyField(to='administracion.Aplicacion')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.AddField(
            model_name='robots',
            name='DESARROLLO',
            field=models.ForeignKey(limit_choices_to={'TIPO': 'Desarrollo'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='robots_desarrollo', to='administracion.servidores'),
        ),
        migrations.AddField(
            model_name='robots',
            name='GERENCIA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.Gerencia'),
        ),
        migrations.AddField(
            model_name='robots',
            name='PRODUCCION',
            field=models.ForeignKey(limit_choices_to={'TIPO': 'Produccion'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='robots_produccion', to='administracion.servidores'),
        ),
        migrations.AddField(
            model_name='robots',
            name='PROVEEDOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.Proveedor', verbose_name='DESARROLLADOR'),
        ),
        migrations.AddField(
            model_name='robots',
            name='TEST',
            field=models.ForeignKey(limit_choices_to={'TIPO': 'Test'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='robots_test', to='administracion.servidores'),
        ),
        migrations.AddField(
            model_name='robots',
            name='USUARIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.Usuario'),
        ),
        migrations.CreateModel(
            name='reprocesoRobot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REPROCESAR', models.TextField(verbose_name='DETALLE')),
                ('ROBOT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.robots')),
            ],
            options={
                'verbose_name': 'Paso',
                'verbose_name_plural': 'Pasos para reprocesar',
            },
        ),
        migrations.CreateModel(
            name='incidencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ESTADO', models.CharField(blank=True, choices=[('Recibido', 'Recibido'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='Recibido', max_length=30, null=True)),
                ('N_INCIDENTE', models.IntegerField(unique=True)),
                ('NOMBRE_INDICENCIA', models.CharField(max_length=100)),
                ('FECHA_SOLICITUD', models.DateField()),
                ('DESCRIPCION_INCIDENCIA', models.CharField(max_length=255)),
                ('DESCRIPCION_SOLUCION', models.CharField(blank=True, max_length=255, null=True)),
                ('ULTIMA_ACTUALIZACION', models.DateField(auto_now_add=True)),
                ('COMENTARIOS', models.TextField(blank=True, null=True)),
                ('ASIGNADO_A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Usuario')),
                ('ROBOT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.robots')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
            },
        ),
        migrations.CreateModel(
            name='ejecucionesProcesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO_EJECUCION', models.CharField(choices=[('Diario', 'Diario'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Diario', max_length=20)),
                ('DOM', models.BooleanField(default=False)),
                ('LUN', models.BooleanField(default=False)),
                ('MAR', models.BooleanField(default=False)),
                ('MIE', models.BooleanField(default=False)),
                ('JUE', models.BooleanField(default=False)),
                ('VIE', models.BooleanField(default=False)),
                ('SAB', models.BooleanField(default=False)),
                ('CANTIDAD_EJECUCIONES_MENSUALES', models.IntegerField(blank=True, default=0, null=True)),
                ('ESPACIO_AGENDA_MIN', models.IntegerField(blank=True, default=15, null=True, verbose_name='MINUTOS RESERVADOS EN AGENDA')),
                ('EJECUCIONES_ACUMULADO', models.BigIntegerField(blank=True, null=True, verbose_name='ACUM. EJECUCIONES (30 dias)')),
                ('DURACION_TAREA_MINUTOS_MANUAL', models.IntegerField(null=True, verbose_name='DURACION DE LA TAREA (manualmente) Min.')),
                ('DURACION_MENSUAL', models.IntegerField(null=True, verbose_name='HS LABORABLES MENSUALES')),
                ('TIPO_ESFUERZO', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], default='Medio', max_length=10)),
                ('FTE', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='FTE')),
                ('CONSUMO_TOTAL', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='TOTAL HORAS AGENDA (mensual)')),
                ('COMENTARIOS', models.TextField(blank=True, null=True)),
                ('FECHA_INICIO', models.DateField(blank=True, null=True)),
                ('HORA_INICIO_EJECUCION', models.TimeField(blank=True, null=True)),
                ('HORA_FIN_CALCULADA', models.TimeField(blank=True, null=True)),
                ('LISTA', models.TextField(blank=True, null=True)),
                ('ROBOT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.robots')),
                ('SERVIDOR', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.servidores')),
            ],
            options={
                'verbose_name': 'Ejecucion',
                'verbose_name_plural': 'Ejecuciones',
            },
        ),
        migrations.CreateModel(
            name='aplicacionesServidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APLICACION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Aplicacion')),
                ('SERVIDOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.servidores')),
            ],
            options={
                'verbose_name': 'Aplicacion',
                'verbose_name_plural': 'Aplicaciones instaladas',
            },
        ),
        migrations.CreateModel(
            name='aplicacionesRobot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APLICACION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Aplicacion')),
                ('ROBOT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.robots')),
            ],
            options={
                'verbose_name': 'Aplicacion',
                'verbose_name_plural': 'Aplicaciones utilizadas',
            },
        ),
    ]
