# Generated by Django 4.2.1 on 2023-05-18 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aplicacionesRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VERSION', models.CharField(blank=True, max_length=255, null=True)),
                ('APLICACION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.aplicacion')),
                ('ROBOT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.robots')),
            ],
            options={
                'verbose_name': 'Aplicacion',
                'verbose_name_plural': 'Aplicaciones instaladas',
            },
        ),
    ]
