# Generated by Django 4.2.1 on 2023-05-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_aplicacionesrobot'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='APLICACIONES_USADAS',
            field=models.ManyToManyField(to='administracion.aplicacion'),
        ),
    ]
