# Generated by Django 4.2.1 on 2023-05-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_robots_aplicaciones_usadas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacionesrobot',
            options={'verbose_name': 'Aplicacion', 'verbose_name_plural': 'Aplicaciones usadas'},
        ),
        migrations.RemoveField(
            model_name='aplicacionesrobot',
            name='VERSION',
        ),
        migrations.RemoveField(
            model_name='aplicacionesservidores',
            name='VERSION',
        ),
    ]
