# Generated by Django 4.2.1 on 2023-05-18 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_aplicacionesrobot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.TextField(blank=True, null=True)),
                ('Fecha', models.DateField(blank=True, null=True)),
                ('HoraEjecucion', models.TextField(blank=True, null=True)),
                ('Proceso', models.TextField(blank=True, null=True)),
                ('Gerencia', models.TextField(blank=True, null=True)),
                ('Mensaje', models.TextField(blank=True, null=True)),
                ('Duracion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Duracion Minutos')),
                ('Server', models.TextField(blank=True, null=True)),
                ('Paquete', models.TextField(blank=True, null=True)),
                ('Comentarios', models.CharField(blank=True, max_length=120, null=True)),
                ('clave', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Monitoreo',
                'verbose_name_plural': 'Monitoreos',
            },
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Desarrollador', 'verbose_name_plural': 'Desarrolladores'},
        ),
        migrations.CreateModel(
            name='incidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_INCIDENTE', models.CharField(max_length=255, unique=True)),
                ('NOMBRE_INDICENCIA', models.CharField(blank=True, max_length=100, null=True)),
                ('FECHA_SOLICITUD', models.DateField()),
                ('ESTADO', models.CharField(blank=True, choices=[('Recibido', 'Recibido'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='Recibido', max_length=30, null=True)),
                ('DESCRIPCION_INCIDENCIA', models.CharField(blank=True, max_length=255, null=True)),
                ('DESCRIPCION_SOLUCION', models.CharField(blank=True, max_length=255, null=True)),
                ('ULTIMA_ACTUALIZACION', models.DateField(auto_now_add=True)),
                ('COMENTARIOS', models.TextField(blank=True, null=True)),
                ('ASIGNADO_A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.usuario')),
                ('ROBOT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.robots')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
            },
        ),
    ]
