# Generated by Django 4.2.1 on 2023-05-18 01:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_monitoreo_alter_proveedor_options_incidencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.TextField(blank=True, null=True)),
                ('FECHA_INICIO', models.DateField(blank=True, null=True)),
                ('FECHA_FIN', models.DateField(blank=True, null=True)),
                ('TIEMPO_INVERTIDO', models.TimeField(blank=True, default=datetime.timedelta(seconds=1800), null=True)),
                ('ESTADO', models.CharField(choices=[('No inciado', 'No inciado'), ('inciado', 'inciado'), ('Esperando Respuesta', 'Esperando Respuesta'), ('Finalizada', 'Finalizada')], default='No inciado', max_length=30)),
                ('GERENCIA_A_IMPUTAR', models.CharField(blank=True, max_length=255, null=True)),
                ('COMENTARIOS', models.TextField(blank=True, null=True)),
                ('ROBOT_ASOCIADO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.robots')),
            ],
        ),
    ]
