# Generated by Django 4.2.1 on 2023-05-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='REPROCESAR',
            field=models.TextField(default=63),
            preserve_default=False,
        ),
    ]
