# Generated by Django 4.2.1 on 2023-05-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_robots_reprocesar'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionesrobot',
            name='REPROCESAR',
            field=models.TextField(default=67),
            preserve_default=False,
        ),
    ]
