# Generated by Django 4.2.1 on 2023-05-18 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_aplicacionesrobot_reprocesar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacionesrobot',
            name='REPROCESAR',
        ),
        migrations.CreateModel(
            name='reprocesoRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REPROCESAR', models.TextField()),
                ('ROBOT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.robots')),
            ],
        ),
    ]
