# Generated by Django 4.2.1 on 2023-05-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_remove_aplicacionesrobot_reprocesar_reprocesorobot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reprocesorobot',
            name='ARCHIVO_CONFIG',
            field=models.CharField(default=63, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reprocesorobot',
            name='RUTAS_INPUT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reprocesorobot',
            name='RUTAS_OUTPUT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
