# Generated by Django 4.2.1 on 2023-05-18 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_alter_robots_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robots',
            name='PROVEEDOR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.proveedor', verbose_name='DESARROLLADOR'),
        ),
    ]
