# Generated by Django 4.2.1 on 2023-05-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_remove_reprocesorobot_archivo_config_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacionesrobot',
            options={'verbose_name': 'Aplicacion', 'verbose_name_plural': 'Aplicaciones utilizadas'},
        ),
        migrations.AlterModelOptions(
            name='reprocesorobot',
            options={'verbose_name': 'Paso', 'verbose_name_plural': 'Pasos para reprocesar'},
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='N_INCIDENTE',
            field=models.CharField(max_length=255),
        ),
    ]
