# Generated by Django 4.2.1 on 2023-05-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_alter_incidencias_n_incidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencias',
            name='DESCRIPCION_INCIDENCIA',
            field=models.CharField(default=8, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='NOMBRE_INDICENCIA',
            field=models.CharField(default=86, max_length=100),
            preserve_default=False,
        ),
    ]
