# Generated by Django 4.2.1 on 2023-05-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_alter_incidencias_descripcion_incidencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'verbose_name': 'Monitoreo', 'verbose_name_plural': 'Monitoreos'},
        ),
        migrations.AlterField(
            model_name='tarea',
            name='NOMBRE',
            field=models.TextField(default=74),
            preserve_default=False,
        ),
    ]
