# Generated by Django 4.2.1 on 2023-05-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0021_monitoreo_alter_tarea_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacion',
            options={'verbose_name': 'Aplicacion', 'verbose_name_plural': 'ABM Aplicaciones'},
        ),
        migrations.AlterModelOptions(
            name='gerencia',
            options={'verbose_name': 'Gerencia', 'verbose_name_plural': 'ABM Gerencias'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Desarrollador', 'verbose_name_plural': 'ABM Desarrolladores'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'ABM Usuarios'},
        ),
        migrations.RemoveField(
            model_name='robots',
            name='SERVIDOR',
        ),
        migrations.AddField(
            model_name='robots',
            name='DESARROLLO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='robots_desarrollo', to='administracion.servidores'),
        ),
        migrations.AddField(
            model_name='robots',
            name='PRODUCCION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='robots_produccion', to='administracion.servidores'),
        ),
        migrations.AddField(
            model_name='robots',
            name='TEST',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='robots_test', to='administracion.servidores'),
        ),
    ]
