# Generated by Django 4.2.1 on 2023-05-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0022_alter_aplicacion_options_alter_gerencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robots',
            name='DESARROLLO',
            field=models.ForeignKey(default=1, limit_choices_to={'TIPO': 'Desarrollo'}, on_delete=django.db.models.deletion.PROTECT, related_name='robots_desarrollo', to='administracion.servidores'),
        ),
        migrations.AlterField(
            model_name='robots',
            name='PRODUCCION',
            field=models.ForeignKey(default=1, limit_choices_to={'TIPO': 'Produccion'}, on_delete=django.db.models.deletion.PROTECT, related_name='robots_produccion', to='administracion.servidores'),
        ),
        migrations.AlterField(
            model_name='robots',
            name='TEST',
            field=models.ForeignKey(default=1, limit_choices_to={'TIPO': 'Test'}, on_delete=django.db.models.deletion.PROTECT, related_name='robots_test', to='administracion.servidores'),
        ),
        migrations.AlterField(
            model_name='servidores',
            name='TIPO',
            field=models.CharField(choices=[('Desarrollo', 'Desarrollo'), ('Test', 'Test'), ('Produccion', 'Produccion')], default=1, max_length=20),
        ),
    ]
