# Generated by Django 4.2.1 on 2023-05-19 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0024_alter_incidencias_asignado_a_alter_incidencias_robot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robots',
            name='DESARROLLO',
            field=models.ForeignKey(limit_choices_to={'TIPO': 'Desarrollo'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='robots_desarrollo', to='administracion.servidores'),
        ),
        migrations.AlterField(
            model_name='robots',
            name='PRODUCCION',
            field=models.ForeignKey(limit_choices_to={'TIPO': 'Produccion'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='robots_produccion', to='administracion.servidores'),
        ),
        migrations.AlterField(
            model_name='robots',
            name='TEST',
            field=models.ForeignKey(limit_choices_to={'TIPO': 'Test'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='robots_test', to='administracion.servidores'),
        ),
    ]
