# Generated by Django 4.2.1 on 2023-05-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0025_alter_robots_desarrollo_alter_robots_produccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robots',
            name='REPROCESAR',
            field=models.TextField(blank=True, null=True),
        ),
    ]
